### ISSUE TITLE
index.html: Косяки

### ISSUE THREAD

**Issue by VladimirVaivada** [NeroOren/Nerooren.github.io#2]
- [x] Изменить значение атрибута _lang_ на русский язык, если он у тебя основной на странице
- [x] Для адаптивности, добавить мета-тег _viewport_
- [x] Добавить мета-тег _description_ с описанием основного контента страницы (в т.ч. для SEO)
- [x] Привести в порядок отступы, избавиться от пробелов в пустых строках и на концах строк, если будут. Это улучшит читаемость кода, да и просто будет выглядеть опрятнее.
- [x] Закрыть все парные теги
- [x] Список навигационных ссылок следует разметить списком, а не просто набором дивов
- [x] Навести порядок в именовании классов, например ссылка это не button, а блок заголовков тем более
- [x] Использовать семантические теги _header_, _nav_, _main_, _footer_ и пр.
- [x] Для подзаголовка, того же раздела лучше использовать не _h2_ а простой _p_

**Comment by DmitrySerif** [comment]
Готово!

**Comment by VladimirVaivada** [comment]
- [ ] Тег description должен содержать полноценный текст описание страницы, этот текст будет отображаться в результатах поиска. Ключевые слова прописывают в тег keywords.
- [ ] Тег title лучше дополнить указателем на текущую страницу, например 'Главная - NeroX'
- [ ] Поставь и настрой себе плагин Prettier в VSCode, или сам отслеживай отступы и пробелы в конце строк (trailing whitespaces). А то у тебя получается микс из табов и пробелов, некоторые комменты закрыты не на одном уровне с открывающими, и полно пробелов в конце строк...
- [ ] Не стоит, как мне кажется, создавать обёртки div просто прозапас, надо только когда без них ну никак, равно как и отдельный div для фоновой картинки...
- [ ] Разделы всегда должны содержать заголовок правильного уровня, как первый дочерний элемент (section>h2), если в визуальном представлении он не применяется - пользую специальный класс, который скроет его визуально но оставит для скрин ридеров, браузера и роботов (читай про visually-hidden)
- [ ] Не стоит помещать текст в div, лучше применять специфичные теги типа h, p, blockquote, span и т.п.
- [ ] Форма на одних дивах это прям плохо, используй тег form и пр. для оформления ввода данных пользователем даже если для обмена данными будешь использовать js
- [ ] Имена классов ещё не полностью соответствуют логике БЭМ. Например, footer и дочерний footer-container - хочешь сказать что footer-container это независимый блок который можно применять вне контекста блока footer? Если нет, то надо писать footer__container, а вообще надо подумать нужен ли тебе такой обобщенный контейнер в этом месте... Да ещё и с дополнительной обёрткой inner
- [ ] Обрати внимание, у тебя все стили висят исключительно на классах элементов, классы блоков вообще ни за что не отвечают...
- [ ] Для сброса стилей в начале лучше применять проверенные решения из normalize.css, bootstrap reboot.css и подобных, естественного взяв из них только необходимые тебе части...
