### ISSUE TITLE
style.css: Косяки

### ISSUE THREAD

**Issue by VladimirVaivada** [NeroOren/Nerooren.github.io#3]
- [x] Неправильно используешь селекторы по тегам (точка в начале не нужна)
- [x] Селекторы по тегам лучше вообще не использовать, это ухудшает поддерживаемость и масштабируемость. Лучше полностью перейти на БЭМ или атомарный CSS
- [x] Привести в порядок отступы, разделять блоки правил пустыми строками, правила либо группировать по категориям, либо упорядочить по алфавиту
- [x] Tip: Для переноса элементов на новую строку флекс контейнера используй свойство flex-wrap

**Comment by DmitrySerif** [comment]
Close:D
